### ISSUE TITLE
separate code

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-511#24]
modify code, so that you create Makefile and place only your code in the directory, call swagger code gen from the makefile, than copy the controller_*.py code to generate code and overwrite swagger code gen. 

this way no other code has to be stored

TAs got explanation on this so they can help if unclear, but in general we do not want the entire directory ti be in github, but only the code you modified and control via the makefile to place them into the right dir.

**Comment by Sandeep-K-Khandelwal** [comment]
Sure Professor, will work on this.

**Comment by Sandeep-K-Khandelwal** [comment]
Thanks Professor.

I have implemented all the comments & checked in the code. Please have a look and lt me know.

- Added container tag in the Makefile to create the container exposing the service
- Updated the directory structure as per requirement
- updated REST service functionality to filter the data based on the regular expression provided

**Comment by Sandeep-K-Khandelwal** [comment]
Closing the issue.
