### ISSUE TITLE
see comments about section/headline in tutorial

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-511#25]

**Comment by Sandeep-K-Khandelwal** [comment]
Thanks professor. Will work on the comments.

**Comment by Sandeep-K-Khandelwal** [comment]
Hi Professor

I have implemented all the comments.

Assigning the issue to you for review and closure.

Thanks,
Sandeep

**Comment by Sandeep-K-Khandelwal** [comment]
Hi Professor, can you please close the comment as the review comments are implemented.

**Comment by laszewsk** [comment]
this is your responsibility

**Comment by Sandeep-K-Khandelwal** [comment]
ok Professor. Closing this issue now.
