### ISSUE TITLE
Draft Project Paper template in github

### ISSUE THREAD

**Issue by Sandeep-K-Khandelwal** [cloudmesh-community/hid-sp18-511#29]
Waiting for the approval from the Professor.

**Comment by Sandeep-K-Khandelwal** [comment]
Have updated the propoal document in https://github.com/cloudmesh-community/hid-sp18-511/tree/master/project-paper

Updated the Good document https://docs.google.com/document/d/14L0guBfWJdRqqf1BoLw41LPg9HU3BqROFZeF43hJF_E/edit with project details.

Waiting for the professor to review and approve.

**Comment by laszewsk** [comment]
grammar spelling errors, do not use ~ before citation, all documented in the handbook
use checklist from the handbook and 
use chktex
check documents before asking for a review
review use of a/the

scope is ok, but does not include that the script can also be started from a swagger service to start the deployment. once you go the cluster deployed you may want to look at that. Also, i pointed to an existing project that does this already, but maybe a bit outdated, maybe you want to use that and improve?

**Comment by Sandeep-K-Khandelwal** [comment]
Hi Professor, thanks for the review comments.

I will work on the comments.

Thanks,
Sandeep

**Comment by Sandeep-K-Khandelwal** [comment]
Hi Professor,

I have updated the proposal document & fixed all grammer related issues.

Also, did run the chktex and didn't find any issue. Here is the ouput of the chktext run -

(2.7.13) student@student-VirtualBox:~/github/cloudmesh-community/hid-sp18-511/project-paper$ chktex content.tex 
ChkTeX v1.7.4 - Copyright 1995-96 Jens T. Berger Thielemann.
Compiled with PCRE regex support.
No errors printed; No warnings printed; No user suppressed warnings; No line suppressed warnings.

Please let me know what time would be convinient for you to discuss about the project progress.

Thanks,
Sandeep

**Comment by Sandeep-K-Khandelwal** [comment]
Closing this issue.
